// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622193527_AddLastDailyBonus")]
    partial class AddLastDailyBonus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("backend.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Happiness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hunger")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDailyBonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coins = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 0,
                            Happiness = 80,
                            Health = 100,
                            Hunger = 50,
                            IsAlive = true,
                            Level = 1,
                            Name = "Пухнастик",
                            Species = "Кіт"
                        },
                        new
                        {
                            Id = 2,
                            Coins = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 0,
                            Happiness = 90,
                            Health = 95,
                            Hunger = 30,
                            IsAlive = true,
                            Level = 1,
                            Name = "Бульбазавр",
                            Species = "Ящірка"
                        },
                        new
                        {
                            Id = 3,
                            Coins = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 0,
                            Happiness = 60,
                            Health = 85,
                            Hunger = 70,
                            IsAlive = true,
                            Level = 1,
                            Name = "Зірочка",
                            Species = "Собака"
                        });
                });

            modelBuilder.Entity("backend.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HappinessEffect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthEffect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HungerEffect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Effect = "Їжа",
                            HappinessEffect = 5,
                            HealthEffect = 0,
                            HungerEffect = -30,
                            Name = "Риба",
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Effect = "Їжа",
                            HappinessEffect = 10,
                            HealthEffect = 0,
                            HungerEffect = -50,
                            Name = "М'ясо",
                            Price = 20
                        },
                        new
                        {
                            Id = 3,
                            Effect = "Їжа",
                            HappinessEffect = 20,
                            HealthEffect = -5,
                            HungerEffect = -10,
                            Name = "Цукерка",
                            Price = 5
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
